In [14]:
import numpy as np
import pandas as pd

In [3]:
v = np.array([1,2,1,2,3,3,3,3])

In [4]:
np.mean(v)

2.25

In [5]:
np.median(v)

2.5

In [6]:
v.sum()

18

In [7]:
v.min()

1

In [8]:
np.var(v)

0.6875

In [10]:
# 3x + y = 9
# x + 2y = 8 denklemlerinin çözüm kümesini bulalım

a = np.array([[3,1],[1,2]])
b = np.array([9,8])

In [11]:
a

array([[3, 1],
       [1, 2]])

In [12]:
b

array([9, 8])

In [13]:
np.linalg.solve(a,b)

array([2., 3.])

In [15]:
pd.Series([10,88,3,5,4])

0    10
1    88
2     3
3     5
4     4
dtype: int64

In [16]:
ser = pd.Series([10,88,3,5,4])

In [18]:
type(ser)

pandas.core.series.Series

In [19]:
ser.dtype

dtype('int64')

In [20]:
ser.size

5

In [21]:
ser.ndim

1

In [22]:
ser.values

array([10, 88,  3,  5,  4])

In [23]:
type(ser.values)

numpy.ndarray

In [25]:
for i in ser.values:
  print(i)

10
88
3
5
4


In [26]:
[i for i in ser.values]

[10, 88, 3, 5, 4]

In [27]:
ser.hasnans

False

In [29]:
ser.head(3)

0    10
1    88
2     3
dtype: int64

In [30]:
pd.Series([i for i in "abdullah"])

0    a
1    b
2    d
3    u
4    l
5    l
6    a
7    h
dtype: object

In [33]:
labels = ["a","b","c"]
my_list =[10,20,30]
arr = np.array([10,20,30])
d = {"a": 10 , "b": 25, "c": 35}

In [35]:
pd.Series(data = my_list)

0    10
1    20
2    30
dtype: int64

In [36]:
pd.Series(data = my_list, index= labels)

a    10
b    20
c    30
dtype: int64

In [37]:
pd.Series(my_list,labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
# using numpy arrays

In [39]:
arr

array([10, 20, 30])

In [38]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [40]:
pd.Series(arr, labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
# using dict

In [41]:
d

{'a': 10, 'b': 25, 'c': 35}

In [42]:
pd.Series(d)

a    10
b    25
c    35
dtype: int64

In [43]:
pd.Series(d, ["w","c","z"])

w     NaN
c    35.0
z     NaN
dtype: float64

In [44]:
a = np.nan

In [45]:
a

nan

In [ ]:
# data series

In [46]:
labels 

['a', 'b', 'c']

In [47]:
pd.Series(data = labels)

0    a
1    b
2    c
dtype: object

In [48]:
pd.Series([sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [49]:
mix_data = ["a",1 , True]
pd.Series(mix_data) 

0       a
1       1
2    True
dtype: object

In [50]:
s = pd.Series(["p","q","e","s"],index=[3,5,7,9])
s.sort_index()

3    p
5    q
7    e
9    s
dtype: object

In [52]:
s.sort_index(ascending=False) # default değeri true'dur , false yapılırsa büyükten kucuge sıralar

9    s
7    e
5    q
3    p
dtype: object

In [53]:
s.sort_index(ascending=True)

3    p
5    q
7    e
9    s
dtype: object

In [54]:
ser.sort_index()

0    10
1    88
2     3
3     5
4     4
dtype: int64

In [55]:
s = pd.Series(["q","p","r","s"], index=[2,3,6,np.nan])

In [56]:
s.sort_index(na_position="first") # non değerler normalde sonda yazdırılır, first yazarak başa alabiliriz


NaN    s
2.0    q
3.0    p
6.0    r
dtype: object

In [57]:
s = pd.Series([np.nan,2,3,6,9,8])

In [58]:
s

0    NaN
1    2.0
2    3.0
3    6.0
4    9.0
5    8.0
dtype: float64

In [59]:
s.sort_values(ascending=True) # değerlerden none olanı en sonda döndürür

1    2.0
2    3.0
3    6.0
5    8.0
4    9.0
0    NaN
dtype: float64

In [62]:
s.isin([2]) # isin hangi satırlarda olduğunu bulabiliriz


0    False
1     True
2    False
3    False
4    False
5    False
dtype: bool

In [61]:
s.isin(["a"])

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [63]:
# indexleme

In [64]:
ser1 = pd.Series([1,2,3,4],index=["USA","GERMANY","CANADA","JAPAN"])

In [65]:
ser1

USA        1
GERMANY    2
CANADA     3
JAPAN      4
dtype: int64

In [66]:
ser1["USA"]

1

In [67]:
ser1[0]

1

In [68]:
labels

['a', 'b', 'c']

In [69]:
ser3 = pd.Series(data = labels)

In [70]:
ser3

0    a
1    b
2    c
dtype: object

In [71]:
a = np.array([1,2,35,6583,5])
panser = pd.Series(a)

In [72]:
panser

0       1
1       2
2      35
3    6583
4       5
dtype: int64

In [73]:
panser[0]

1

In [74]:
panser[1:3]

1     2
2    35
dtype: int64

In [75]:
panser = pd.Series([121,200,150,99], index = ["ali","veli","ayşe","nur"])

In [76]:
panser

ali     121
veli    200
ayşe    150
nur      99
dtype: int64

In [77]:
panser["ali"]

121

In [79]:
panser[["veli","nur"]]

veli    200
nur      99
dtype: int64

In [82]:
panser["veli" : "nur"] # index isimleri üzerinden gidilirse son indexi de alır


veli    200
ayşe    150
nur      99
dtype: int64

In [83]:
panser[0:3]

ali     121
veli    200
ayşe    150
dtype: int64

In [84]:
panser["ali":"nur"]

ali     121
veli    200
ayşe    150
nur      99
dtype: int64

In [85]:
panser.index

Index(['ali', 'veli', 'ayşe', 'nur'], dtype='object')

In [86]:
panser.values

array([121, 200, 150,  99])

In [88]:
list(panser.items())

[('ali', 121), ('veli', 200), ('ayşe', 150), ('nur', 99)]