In [ ]:
import numpy as np

In [ ]:
liste = [1,2,3,4,5,6,7,8]
a = np.array(liste)
a


array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
type(a)  # değişkeninin tipini aldık

numpy.ndarray

In [ ]:
a.dtype  # dizinin tuttuğu değerlerin tipini aldık. Hepsi aynı tip veri


dtype('int32')

In [ ]:
a.shape  # tek boyutlu olduğu için bu dizi bir vektör

(8,)

In [ ]:
a[-1]

8

In [ ]:
a[2]=8

In [ ]:
a

array([1, 2, 8, 4, 5, 6, 7, 8])

In [ ]:
b = np.array([[1,2,3],[6,7,8]])

In [ ]:
b.shape

(2, 3)

In [ ]:
b[1,1]=0
b

array([[1, 2, 3],
       [6, 0, 8]])

In [ ]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
c.shape

(3, 3)

In [ ]:
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
c[1,1]

5

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full((2,2), -1)

array([[-1, -1],
       [-1, -1]])

In [ ]:
np.empty((3,4))

array([[1.12079879e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 4.75269212e-037, 3.56530452e-057,
        1.77701909e+160],
       [2.00459922e-076, 8.60100133e-067, 1.11645062e+165,
        7.67659979e-042]])

In [ ]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.arange(5,60,3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53,
       56, 59])

In [ ]:
np.linspace(0,10,3)  # default step 50

array([ 0.,  5., 10.])

In [ ]:
np.random.random((3,3))

array([[0.01333497, 0.02191642, 0.47865008],
       [0.87358779, 0.58454595, 0.49378985],
       [0.62843893, 0.15919562, 0.36958412]])

In [ ]:
np.random.randint(5,10, size=(4,4))

array([[9, 5, 7, 7],
       [5, 9, 6, 7],
       [6, 7, 5, 7],
       [7, 7, 5, 5]])

In [ ]:
z= np.random.randint(2,15,size=(5,3))
z

array([[ 7,  8, 13],
       [14,  4, 13],
       [10,  7,  3],
       [13, 14,  7],
       [13, 14,  6]])

In [ ]:
z.shape

(5, 3)

In [ ]:
z=z.reshape(3,5)

In [ ]:
z.shape

(3, 5)

In [ ]:
z.ravel()

array([ 7,  8, 13, 14,  4, 13, 10,  7,  3, 13, 14,  7, 13, 14,  6])

In [ ]:
z.max()

14

In [ ]:
z.min()

3

In [ ]:
z.argmax()

3

In [ ]:
z.argmin()

8

## Stacking

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[-1,3],[7,9]])

In [ ]:
np.hstack((a,b))

array([[ 1,  2, -1,  3],
       [ 3,  4,  7,  9]])

In [ ]:
np.vstack((a,b))

array([[ 1,  2],
       [ 3,  4],
       [-1,  3],
       [ 7,  9]])

In [ ]:
dizi=np.array([0,1,2,3,4,5,6,7,8,9]).reshape(5,2)
dizi

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
dizi_1=np.array([3,4,5,6,7,8,9,10,11,12]).reshape(5,2)
dizi_1

array([[ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
np.concatenate([dizi,dizi_1], axis=0)  # Satır bazlı alt alta birleştirme

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
np.concatenate([dizi,dizi_1], axis=1)  # sütun bazlı yan yana birleştirme

array([[ 0,  1,  3,  4],
       [ 2,  3,  5,  6],
       [ 4,  5,  7,  8],
       [ 6,  7,  9, 10],
       [ 8,  9, 11, 12]])

In [ ]:
array_1 = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12]])

In [ ]:
array_1.shape

(3, 4)

In [ ]:
array_1[:2, 1:3]

array([[2, 3],
       [6, 7]])

In [ ]:
array_2 = array_1.copy()
array_2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
array_2[1][1] = -6
array_2

array([[ 1,  2,  3,  4],
       [ 5, -6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# ">" ve "<" koşullarını artık yazmaya gerek yok ezberledik :D

## Matematiksel İşlemler

In [1]:
x = np.array([[1,2],[3,4]])
y = np.array([[1,3],[7,9]])

NameError: ignored

In [ ]:
x+y

array([[ 2,  5],
       [10, 13]])

In [ ]:
x-y

array([[ 0, -1],
       [-4, -5]])

In [ ]:
np.subtract(x,y)

array([[ 0, -1],
       [-4, -5]])

In [ ]:
np.multiply(x,y)

array([[ 1,  6],
       [21, 36]])

In [ ]:
x*y

array([[ 1,  6],
       [21, 36]])

In [ ]:
np.dot(x,y)

array([[15, 21],
       [31, 45]])

In [ ]:
x@y

array([[15, 21],
       [31, 45]])

In [ ]:
x/y

array([[1.        , 0.66666667],
       [0.42857143, 0.44444444]])

In [ ]:
np.divide(x,y)

array([[1.        , 0.66666667],
       [0.42857143, 0.44444444]])

In [ ]:
x

array([[1, 2],
       [3, 4]])

In [ ]:
x**2

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [ ]:
x1=np.square(x)
x1

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [ ]:
np.sqrt(x1)

array([[1., 2.],
       [3., 4.]])

In [ ]:
np.exp(3)  # logaritmadaki e = exp, bu işlem e**3

20.085536923187668

In [ ]:
np.log(100)

4.605170185988092

In [ ]:
np.log10(100)

2.0

In [ ]:
t = np.array([np.pi/6, np.pi/2, np.pi/3])
t

array([0.52359878, 1.57079633, 1.04719755])

In [ ]:
np.sin(t)

array([0.5      , 1.       , 0.8660254])