In [2]:
import numpy as np

In [3]:
a = [1, 3, 5, 7]
a = np.array(a)
a

array([1, 3, 5, 7])

In [4]:
a = [1, 3, 5, 7]
b = [2, 4 ,6, 8]
c = [3, 6, 9,12]
a = np.array(a)
a = np.array(a)
b = np.array(b)
c = np.array(c)
d = a*b*c
d = list(d)
print(d)

[6, 72, 270, 672]


In [7]:
d = np.array([3.14,14,15,16])
type(d)
d.dtype

dtype('float64')

In [8]:
np.arange(4,20).reshape(8,2)

array([[ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [9]:
np.random.randint(3,9, size = (4,8))

array([[7, 5, 7, 3, 8, 5, 7, 6],
       [3, 4, 8, 8, 7, 8, 4, 6],
       [3, 8, 7, 6, 7, 6, 8, 4],
       [7, 7, 7, 7, 3, 3, 8, 4]])

In [19]:
a = np.arange(1,16,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [20]:
a.reshape(2,4)

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15]])

In [123]:
a = np.random.randint(2,7, size = (3,4))
b = np.random.randint(8,14, size = (3,4))
c = np.concatenate([a,b])
c

array([[ 6,  2,  6,  6],
       [ 3,  5,  6,  3],
       [ 2,  2,  5,  5],
       [ 9, 10, 13, 10],
       [ 9,  8, 13, 11],
       [ 9,  9, 10, 11]])

In [120]:
c=np.concatenate([a,b], axis=1) # satır sayıları eşit olması gerekir
c                               #  

array([[ 2,  5,  2,  5,  9,  8,  9,  8],
       [ 3,  4,  2,  4, 10, 12, 13, 12],
       [ 3,  5,  4,  6, 12, 13,  9, 11]])

In [33]:
c.ndim  #boyut

2

In [34]:
c.mean()

7.208333333333333

In [35]:
c.var()

15.831597222222223

In [36]:
c.std()

3.978893969713471

In [37]:
np.sort(c) # Bir dizinin sıralanmış bir kopyasını döndürür.
           # Default axis = 1 dir

array([[ 3,  4,  5,  5,  9, 10, 11, 11],
       [ 2,  2,  3,  6, 10, 11, 12, 13],
       [ 2,  2,  3,  4, 10, 11, 12, 12]])

In [38]:
np.sort(c, axis=0)  

array([[ 2,  2,  2,  3,  9, 10, 10, 10],
       [ 3,  3,  2,  4, 11, 11, 12, 11],
       [ 6,  5,  5,  4, 13, 11, 12, 12]])

In [39]:
np.sort(c, axis=1) # satırları sıralar

array([[ 3,  4,  5,  5,  9, 10, 11, 11],
       [ 2,  2,  3,  6, 10, 11, 12, 13],
       [ 2,  2,  3,  4, 10, 11, 12, 12]])

In [40]:
 a

array([[3, 5, 5, 4],
       [6, 2, 2, 3],
       [2, 3, 2, 4]])

In [41]:
a[0]

array([3, 5, 5, 4])

In [42]:
a[2]

array([2, 3, 2, 4])

In [44]:
a[0:3,3] # 0,1,2 ve 3. indexlerin 3.elemanını döndür

array([4, 3, 4])

In [47]:
a[0:2,0:3] # 0,1 ve 2. indexlerin 0,1 ve 2. elemanlarını döndür

array([[3, 5, 5],
       [6, 2, 2]])

In [49]:
a[0:2,0:4]

array([[3, 5, 5, 4],
       [6, 2, 2, 3]])

In [50]:
c

array([[ 3,  5,  5,  4,  9, 11, 10, 11],
       [ 6,  2,  2,  3, 13, 11, 12, 10],
       [ 2,  3,  2,  4, 11, 10, 12, 12]])

In [51]:
c > 8  # elemanlardan 8 den büyük olanları True olmayanları False döndür

array([[False, False, False, False,  True,  True,  True,  True],
       [False, False, False, False,  True,  True,  True,  True],
       [False, False, False, False,  True,  True,  True,  True]])

In [52]:
c[c>8] #   8 den büyük elemanları  döndürür

array([ 9, 11, 10, 11, 13, 11, 12, 10, 11, 10, 12, 12])

In [53]:
len(c[c>8]) # kaç tane oldugunu döndürür

12

In [54]:
c[0:2]>7 # 0 ve 1. indexteki elemanlardan 7'den büyük olanları döndürür.

array([[False, False, False, False,  True,  True,  True,  True],
       [False, False, False, False,  True,  True,  True,  True]])

In [55]:
import seaborn as sb

In [56]:
sb.load_dataset("planets")

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [57]:
sb.load_dataset("tips")

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [58]:
sb.load_dataset("titanic")

survived  pclass     sex   age  ...  deck  embark_town  alive  alone
0           0       3    male  22.0  ...   NaN  Southampton     no  False
1           1       1  female  38.0  ...     C    Cherbourg    yes  False
2           1       3  female  26.0  ...   NaN  Southampton    yes   True
3           1       1  female  35.0  ...     C  Southampton    yes  False
4           0       3    male  35.0  ...   NaN  Southampton     no   True
..        ...     ...     ...   ...  ...   ...          ...    ...    ...
886         0       2    male  27.0  ...   NaN  Southampton     no   True
887         1       1  female  19.0  ...     B  Southampton    yes   True
888         0       3  female   NaN  ...   NaN  Southampton     no  False
889         1       1    male  26.0  ...     C    Cherbourg    yes   True
890         0       3    male  32.0  ...   NaN   Queenstown     no   True

[891 rows x 15 columns]

In [59]:
a 

array([[3, 5, 5, 4],
       [6, 2, 2, 3],
       [2, 3, 2, 4]])

In [60]:
np.add(a,200)  # add fonksiyonu a dan sonra yazdığımız veriyle a nın değerlerini topluyor

array([[203, 205, 205, 204],
       [206, 202, 202, 203],
       [202, 203, 202, 204]])

In [61]:
np.subtract(a,5) # a'nın elemanlarından 5 çıkardı

array([[-2,  0,  0, -1],
       [ 1, -3, -3, -2],
       [-3, -2, -3, -1]])

In [62]:
np.multiply(a,3)

array([[ 9, 15, 15, 12],
       [18,  6,  6,  9],
       [ 6,  9,  6, 12]])

In [63]:
np.mod(a,3)

array([[0, 2, 2, 1],
       [0, 2, 2, 0],
       [2, 0, 2, 1]])

In [64]:
np.absolute(a) # mutlak değer

array([[3, 5, 5, 4],
       [6, 2, 2, 3],
       [2, 3, 2, 4]])

In [65]:
np.cos(a[1])

array([ 0.96017029, -0.41614684, -0.41614684, -0.9899925 ])

In [66]:
np.sin(a[2])

array([ 0.90929743,  0.14112001,  0.90929743, -0.7568025 ])

In [67]:
np.log(a[1,2])

0.6931471805599453

In [68]:
np.log10(a[1])

array([0.77815125, 0.30103   , 0.30103   , 0.47712125])

In [69]:
np.sqrt(16) # karekök

4.0

In [70]:
np.power(4,3) # kuvvet alma

64

In [71]:
np.power(a,2)

array([[ 9, 25, 25, 16],
       [36,  4,  4,  9],
       [ 4,  9,  4, 16]])

In [72]:
np.square(a)

array([[ 9, 25, 25, 16],
       [36,  4,  4,  9],
       [ 4,  9,  4, 16]])

In [73]:
a = np.arange(2,10).reshape(4,2)
a

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [74]:
print(" Array shape is: " ,a.shape)

 Array shape is:  (4, 2)


In [75]:
print(" Array number of element is: " ,a.size)

 Array number of element is:  8


In [76]:
print(" Array number of element is: " , a.itemsize)

 Array number of element is:  8


In [77]:
a.dtype

dtype('int64')

In [78]:
a = np.arange(100,200, 10,).reshape(5,2)
a

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

In [79]:
a = np.array([[11,22,33],[44,55,66],[77,888,99]])
a

array([[ 11,  22,  33],
       [ 44,  55,  66],
       [ 77, 888,  99]])

In [85]:
a[...,-1] # son elemanları listeler

array([33, 66, 99])

In [87]:
a[...,2]  # son elemanları listeler

array([33, 66, 99])

In [88]:
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
sampleArray

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36],
       [39, 42, 45, 48],
       [51, 54, 57, 60]])

In [91]:
sampleArray[::2]

array([[ 3,  6,  9, 12],
       [27, 30, 33, 36],
       [51, 54, 57, 60]])

In [92]:
sampleArray[::2,1::2] # virgülün solu : 0. satırdan başla yani indexten sona kadar 2 atlayarak al demek
                      # virgülün sağı : 1. sütundan başla yani 0.index'in 1. sütunundan başlayarak sona kadar 2 atla demek

array([[ 6, 12],
       [30, 36],
       [54, 60]])

In [95]:
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
c = arrayOne+arrayTwo
c


array([[20, 39, 33],
       [25, 25, 28]])

In [96]:
np.square(c) # karesi

array([[ 400, 1521, 1089],
       [ 625,  625,  784]])

In [99]:
a = np.arange(10,34).reshape(8,3)
a

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33]])

In [103]:
np.split(a,8) # split() fonksiyonu listelerdeki gibi çalışır tek tek elemanlarını alır

[array([[10, 11, 12]]),
 array([[13, 14, 15]]),
 array([[16, 17, 18]]),
 array([[19, 20, 21]]),
 array([[22, 23, 24]]),
 array([[25, 26, 27]]),
 array([[28, 29, 30]]),
 array([[31, 32, 33]])]