In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr[0:5]=100

In [12]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
arr = np.arange(0,11)

In [14]:
slice_of_arr = arr[0:5] 

In [15]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
slice_of_arr[:] = 99

In [18]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [19]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [20]:
arr_copy = arr.copy()

In [21]:
arr_copy[:] = 100

In [22]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [23]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [24]:
arr_2d = np.array([[5,10,15],[5,10,15],[5,10,15]])

In [25]:
arr_2d

array([[ 5, 10, 15],
       [ 5, 10, 15],
       [ 5, 10, 15]])

In [26]:
arr_2d.shape

(3, 3)

In [27]:
arr_2d[0]

array([ 5, 10, 15])

In [28]:
arr_2d[1,1]

10

In [29]:
arr_2d[0,1]

10

In [30]:
arr_2d[:1]

array([[ 5, 10, 15]])

In [31]:
arr_2d[:2]

array([[ 5, 10, 15],
       [ 5, 10, 15]])

In [32]:
arr = np.arange(1,11)

In [33]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [35]:
bool_Arr = arr >3 

In [36]:
bool_Arr

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [37]:
arr[bool_Arr]

array([ 4,  5,  6,  7,  8,  9, 10])

In [38]:
bool_Arr = arr <3 

In [39]:
arr[bool_Arr]

array([1, 2])

In [40]:
arr[arr<3]

array([1, 2])

In [41]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [45]:
# TASK: Use numpy to check how many rolls were greater than 2.
# For example if dice_rolls=[1,2,3] then the answer is 1.