In [1]:
import numpy as np


In [2]:
mylist=[1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
myarr=np.array(mylist)

In [6]:
myarr

array([1, 2, 3])

In [7]:
type(myarr)

numpy.ndarray

In [8]:
my_matrix =[[1,2,3],[4,5,6],[7,8,9]]

In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [19]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [20]:
len(np.linspace(0,5,21))

21

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [23]:
np.random.rand(1)

array([0.59029907])

In [24]:
np.random.rand(5,6)

array([[0.40126477, 0.66076132, 0.66130289, 0.11526789, 0.19636477,
        0.95792788],
       [0.90533354, 0.04076451, 0.43583952, 0.65770797, 0.55786137,
        0.04678102],
       [0.30144743, 0.67358314, 0.49046302, 0.0658052 , 0.93104856,
        0.26173824],
       [0.30791279, 0.82757942, 0.09924934, 0.97211419, 0.07317867,
        0.26806149],
       [0.93971279, 0.32217945, 0.99186222, 0.79775074, 0.77452743,
        0.56587236]])

In [25]:
np.random.rand(5,2)

array([[0.25810541, 0.15880575],
       [0.29566638, 0.75100598],
       [0.92226516, 0.25204477],
       [0.41989887, 0.47043685],
       [0.25841853, 0.22327021]])

In [27]:
np.random.randn(10)
                

array([ 1.45282661,  1.39925349, -0.96996848,  0.24733278,  1.53208029,
       -0.80868105,  0.9831525 , -1.13490061, -1.60087843,  0.01783184])

In [28]:
np.random.randn(2,3)

array([[-0.20097778, -0.58789508,  1.0940511 ],
       [-0.87086624,  0.63236039, -0.25316336]])

In [30]:
np.random.randint(0,101,(5,5))

array([[33, 67, 44, 72, 65],
       [59, 35, 42, 88, 33],
       [49, 73, 14, 37, 32],
       [32, 53, 32, 26, 69],
       [32, 99, 62, 44, 68]])

In [31]:
np.random.randint(0,101,10)

array([81, 52, 93, 61, 59, 21, 54,  0, 43, 35])

In [38]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [39]:
np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [41]:
np.random.seed(42)

np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [42]:
arr = np.arange(0,25)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [44]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [45]:
arr.reshape(5,4)

ValueError: ignored

In [46]:
ranarr = np.random.randint(0,101,10)

In [47]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [48]:
ranarr.max()

99

In [49]:
ranarr.min()

2

In [50]:
ranarr.argmax() # max olan sayının indexini bulur

5

In [51]:
ranarr.argmin()

7

In [52]:
ranarr.dtype

dtype('int64')

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [54]:
arr.shape

(25,)

In [55]:
arr = arr.reshape(5,5)

In [56]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [57]:
arr.shape

(5, 5)

In [58]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [59]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
# TASK: Create a numpy array called myarray which consists of 101 evenly linearly spaced points between 0 and 10.
# MAKE SURE TO READ THE FULL INSTRUCTIONS ABOVE CAREFULLY, AS THE EVALUATION SCRIPT IS VERY STRICT.